# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{load_path_find}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joshua Hull"]
  s.date = %q{2010-01-17}
  s.description = %q{Convenient way to find stuff on the load path.}
  s.email = %q{joshbuddy@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/load_path_find.rb",
    "spec/data/dir1/file1",
    "spec/data/dir1/test.rb",
    "spec/data/dir2/file1",
    "spec/data/dir2/test.rb",
    "spec/load_path_find_spec.rb",
    "spec/spec.opts"
  ]
  s.homepage = %q{http://github.com/joshbuddy/load_path_find}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Convenient way to find stuff on the load path.}
  s.test_files = [
    "spec/data/dir1/test.rb",
    "spec/data/dir2/test.rb",
    "spec/load_path_find_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dirge>, [">= 0.0.3"])
    else
      s.add_dependency(%q<dirge>, [">= 0.0.3"])
    end
  else
    s.add_dependency(%q<dirge>, [">= 0.0.3"])
  end
end

